"""Diagnostic product modules."""

from agent_tracegrad.diagnosis.atomizer import ComponentAtom, atomize_node, atomize_policy_text, atomize_tool_schema
from agent_tracegrad.diagnosis.boundary import (
    BoundaryComponent,
    DecisionBoundaryArtifact,
    build_decision_boundary_artifact,
    decision_boundary_to_dict,
    decision_boundary_to_markdown,
    write_decision_boundary_json,
    write_decision_boundary_markdown,
)
from agent_tracegrad.diagnosis.drill import (
    AtomAttribution,
    DrillResult,
    drill_result_to_dict,
    drill_result_to_markdown,
    run_drill,
    write_drill_json,
    write_drill_markdown,
)
from agent_tracegrad.diagnosis.html_report import (
    diagnosis_to_html,
    landscape_to_html,
    write_diagnosis_html,
    write_landscape_html,
)
from agent_tracegrad.diagnosis.influence import (
    CandidateAction,
    InfluenceCell,
    InfluenceMatrixResult,
    InfluenceRow,
    influence_matrix_to_dict,
    influence_matrix_to_markdown,
    run_influence_matrix,
    write_influence_matrix_json,
    write_influence_matrix_markdown,
)
from agent_tracegrad.diagnosis.landscape import (
    LandscapeCluster,
    LandscapeComponentStats,
    LandscapeResult,
    LandscapeTraceResult,
    landscape_to_dict,
    landscape_to_markdown,
    load_diagnosis_inputs,
    load_trace_inputs,
    run_landscape,
    run_landscape_from_diagnoses,
    write_landscape_json,
    write_landscape_markdown,
)
from agent_tracegrad.diagnosis.patterns import detect_diagnostic_labels, diagnostic_label_to_dict
from agent_tracegrad.diagnosis.report import diagnosis_to_markdown, write_diagnosis_markdown
from agent_tracegrad.diagnosis.runner import (
    diagnosis_to_dict,
    diagnosis_from_dict,
    read_diagnosis_json,
    run_diagnosis,
    write_diagnosis_json,
)
from agent_tracegrad.diagnosis.types import (
    ComponentClassification,
    DiagnosisAblation,
    DiagnosisEvidence,
    DiagnosisResult,
    DiagnosticLabel,
    DiagnosticLabelName,
    MarginContribution,
    MarginDistribution,
)

__all__ = [
    "AtomAttribution",
    "BoundaryComponent",
    "CandidateAction",
    "ComponentAtom",
    "ComponentClassification",
    "DecisionBoundaryArtifact",
    "DiagnosisAblation",
    "DiagnosisEvidence",
    "DiagnosisResult",
    "DiagnosticLabel",
    "DiagnosticLabelName",
    "DrillResult",
    "InfluenceCell",
    "InfluenceMatrixResult",
    "InfluenceRow",
    "LandscapeCluster",
    "LandscapeComponentStats",
    "LandscapeResult",
    "LandscapeTraceResult",
    "MarginContribution",
    "MarginDistribution",
    "atomize_node",
    "atomize_policy_text",
    "atomize_tool_schema",
    "build_decision_boundary_artifact",
    "decision_boundary_to_dict",
    "decision_boundary_to_markdown",
    "detect_diagnostic_labels",
    "diagnostic_label_to_dict",
    "diagnosis_to_html",
    "diagnosis_to_markdown",
    "diagnosis_to_dict",
    "diagnosis_from_dict",
    "drill_result_to_dict",
    "drill_result_to_markdown",
    "influence_matrix_to_dict",
    "influence_matrix_to_markdown",
    "landscape_to_dict",
    "landscape_to_html",
    "landscape_to_markdown",
    "load_diagnosis_inputs",
    "load_trace_inputs",
    "read_diagnosis_json",
    "run_diagnosis",
    "run_drill",
    "run_influence_matrix",
    "run_landscape",
    "run_landscape_from_diagnoses",
    "write_diagnosis_html",
    "write_diagnosis_markdown",
    "write_diagnosis_json",
    "write_decision_boundary_json",
    "write_decision_boundary_markdown",
    "write_drill_json",
    "write_drill_markdown",
    "write_influence_matrix_json",
    "write_influence_matrix_markdown",
    "write_landscape_json",
    "write_landscape_html",
    "write_landscape_markdown",
]
